import {StyleSheet, StatusBar} from 'react-native';
export default StyleSheet.create({
  headerContain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
    elevation: 2,
  },
  middleComponent: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  container: {
    height: '30%',
  },
  amount: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    paddingHorizontal: 15,
  },
  promo: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginVertical: 10,
    paddingHorizontal: 15,
  },
  input: {
    height: 40,
    width: '92%',
    borderWidth: 0,
    borderRadius: 10,
    backgroundColor: 'white',
  },
  next: {
    alignItems: 'center',
  },
  buttonGroup: {
    width: '95%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    paddingBottom: 20,
  },
  btnOutline: {
    width: '40%',
    fontSize: 16,
    borderColor: 'black',
    color: 'black',
    borderWidth: 1.5,
    alignSelf: 'center',
    borderRadius: 30,
    padding: 10,
  },
  btnRounded: {
    width: '50%',
    fontSize: 16,
    alignSelf: 'center',
    color: 'white',
    borderRadius: 30,
    padding: 10,
    backgroundColor: '#FC5859',
  },
  textBtn: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    color: 'white',
    paddingVertical: 2,
  },
  textOutline: {
    color: 'black',
    fontSize: 16,
    textAlign: 'center',
  },
  check: {
    width: '90%',
    height: 48,
    alignSelf: 'center',
    borderRadius: 30,
    padding: 10,
    backgroundColor: '#FC5859',
  },
});
